### ISSUE TITLE
[FEAT] ColorStyles 및 TextStyles 반영, Margin 및 Padding 재검토 (Refactoring)

### ISSUE THREAD

**Issue by hoosong0235** [sparcs-kaist/otl-app#102]
## Description

완료된 페이지
- main_page.dart
- privacy_page.dart
- people_page.dart
- settings_page.dart
- user_page.dart
- course_search_page.dart
- lecture_search_page.dart
- home.dart
- course_detail_page.dart
- lecture_detail_page.dart
- my_review_page.dart
- liked_review_page.dart
- dictionary_page.dart
- review_page.dart

진행중인 페이지
- search_filter_panel.dart SliderSelection부터 (line 250 부근)

진행 예정인 페이지
- timetable_page.dart
등

**Comment by sboh1214** [comment]
timetable_page 는 @lobe 님이 해주셨을 것으로 예상.
search_filter_page는 @star 님 작업 부분이라서 일단 건드리지 않음
