### ISSUE TITLE
[FEAT] Small Issues

### ISSUE THREAD

**Issue by SungyeopJeong** [sparcs-kaist/otl-app#154]
## Description

개별로 처리하기에는 애매한 작은 이슈들을 모아서 정리
- [x] Credit에 '준비 중입니다.' 번역 안 되어 있음
- [x] main page의 schedule의 semester.title이 설정에서 언어 변경 시 바뀌지 않음
- [x] hall of fame의 학기 선택 드롭다운의 스크롤바 interactive할 수 있게 수정
  - hall of fame의 학기 선택 ui 변경하면 필요 X (추후 처리)
- [x] 스플래시 화면 추가
- ~리뷰 신고 메일 템플릿 추가 (feat@popup-redesign에서 해결할 수도)~
- ~앱 내 Color들 OTLColor로 변경~barrier color가 해당되는 관계로 feat@popup-redesign에서 해결

**Comment by sboh1214** [comment]
홈화면에서 과목을 눌렀을 때 해당 과목의 상세 페이지로 이동하지 않음
<img width="300" src="https://github.com/sparcs-kaist/otl-app/assets/30364442/53d052a5-5720-4d81-aff8-b1a47048ae0f">
