### ISSUE TITLE
[FEAT] BackdropScaffold, show에서 Scaffold, Navigation으로의 이전

### ISSUE THREAD

**Issue by hoosong0235** [sparcs-kaist/otl-app#88]
## TODO

1. 모든 **BackdropScaffold**를 **Scaffold**로 이전
2. 모든 **Scaffold**를 **Navigation**으로 이전
3. 페이지별 **Appbar** 설정
4. 페이지별 **Animation** 설정

## DEADLINE

~2023-05-16

## SCREENSHOT

**Comment by sboh1214** [comment]
@hoosong0235 Navigation 라이브러리는 GoRouter 사용하면 좋을 것 같아요~
https://pub.dev/packages/go_router

**Comment by hoosong0235** [comment]
1, 2, 3 **DONE**
